version: 2

sources:
  - name: dbt_ippon_training
    schema: SOURCE
    tables:
      - name: RESTAURANTS
        description: This table contains informations related to the restaurants
      - name: ORDERS
        description: This table contains informations related to the orders
        columns:
          - name: turnover
      - name: DISHES
        description: This table contains informations related to the dishes